version: 2.1

jobs:
  build:
    docker:
      - image: cimg/node:15.1
    steps:
      - checkout

  test:
    docker:
      - image: cimg/node:15.1
    steps:
      - checkout
      - run: cd career-service-webapp && npm install
      - run: cd career-service-webapp && npm run test:ci

workflows:
  workflow-dev:
    jobs:
      - build
      - test:
          requires:
            - build

