version: 2.1

jobs:
  build_and_test:
    docker:
      - image: cimg/node:15.1
    steps:
      - checkout
      - restore_cache:
          key: v1-{{ checksum "career-service-webapp/package-lock.json" }}
      - run: cd career-service-webapp && npm install
      - run: cd career-service-webapp && npm run test:ci
      - save_cache:
          key: v1-{{ checksum "career-service-webapp/package-lock.json" }}
          paths: 
            - career-service-webapp/node_modules
workflows:
  workflow-dev:
    jobs:
      - build_and_test


